export const Estados = Object.freeze({
    ACTIVO: 'ACTIVO',
    INACTIVO: 'INACTIVO',
    EN_REVISION: 'EN_REVISION',
    PENDIENTE_VERIFICACION: 'PENDIENTE_VERIFICACION',
    VERIFICADO: 'VERIFICADO',
    BLOQUEADO: 'BLOQUEADO',
    SUSPENDIDO: 'SUSPENDIDO',
    INHABILITADO: 'INHABILITADO',
    RESTRINGIDO: 'RESTRINGIDO',
    REPORTADO: 'REPORTADO',
    BANEADO: 'BANEADO',
    ELIMINADO: 'ELIMINADO',
});
