export const MENSAJES = {
  REGISTRO_EXITOSO_TITULO: 'REGISTRADO',
  REGISTRO_EXITOSO_MENSAJE: 'SE REGISTRÓ CORRECTAMENTE EL USUARIO',
  CAMPOS_INCOMPLETOS_TITULO: 'CAMPOS INCOMPLETOS',
  CAMPOS_INCOMPLETOS_MENSAJE: 'POR FAVOR, COMPLETA TODOS LOS CAMPOS REQUERIDOS.',
  ERROR_TITULO: 'ERROR',

  CONTRASENIA_NO_COINCIDE: 'LA CONTRASEÑA INGRESADA NO COINCIDE'
};

export const MENSAJES_TITULO = {

}
